#!/usr/bin/env python3
"""Per-page duo palette re-theme for Story Scout Next v2 (Peak Arcade).

Jay's three duos:
  picker  -> Sandy Brown #FAAE7B + Indigo Velvet #432371
  board   -> Raspberry Red #EE005A + Deep Space Blue #012641
  credits -> Antique White #F7E6D2 + Burgundy #90202C

Method: each duo defines a spectrum gradient black -> darker duo color ->
lighter duo color -> white. Every raw palette token is rebound to the
gradient color at the token's own relative luminance, so the whole design
keeps its light/dark structure while every hue falls inside the page's duo
spectrum. Detail/accent tokens (--rasp-*, --sandy-*, --ember, --dusk, --mauve:
hot text, primary buttons, headings, scene skies) are instead rebound to a
complementary gradient built from the 180-degree hue complements of the duo
colors, so details pop in the complementary hue while staying inside the
color scheme. Components, semantic roles, and the SVG background scenes all
reference these tokens, so no markup or component CSS changes.

Home page (no data-page attribute) is untouched.
"""
import colorsys
import re

DUOS = {
    "picker":  ("#FAAE7B", "#432371"),  # sandy brown + indigo velvet
    "board":   ("#EE005A", "#012641"),  # raspberry red + deep space blue
    "credits": ("#F7E6D2", "#90202C"),  # antique white + burgundy
}

# Tokens that render details/accents: rebound to the complementary gradient.
DETAIL_TOKENS = {
    "--rasp-700", "--rasp-600", "--rasp-400", "--rasp-200",
    "--sandy-800", "--sandy-700", "--sandy-600", "--sandy-400", "--sandy-200",
    "--ember", "--dusk", "--mauve",
}

def hex_to_rgb(h):
    h = h.lstrip("#")
    return tuple(int(h[i:i + 2], 16) for i in (0, 2, 4))

def rgb_to_hex(rgb):
    return "#%02X%02X%02X" % tuple(max(0, min(255, int(round(c)))) for c in rgb)

def complement(h):
    """180-degree hue complement, saturation and lightness preserved."""
    r, g, b = (c / 255.0 for c in hex_to_rgb(h))
    hh, ll, ss = colorsys.rgb_to_hls(r, g, b)
    r2, g2, b2 = colorsys.hls_to_rgb((hh + 0.5) % 1.0, ll, ss)
    return rgb_to_hex((r2 * 255, g2 * 255, b2 * 255))

def rel_lum(rgb):
    def lin(c):
        c /= 255.0
        return c / 12.92 if c <= 0.04045 else ((c + 0.055) / 1.055) ** 2.4
    r, g, b = (lin(c) for c in rgb)
    return 0.2126 * r + 0.7152 * g + 0.0722 * b

def lerp(a, b, t):
    return tuple(x + (y - x) * t for x, y in zip(a, b))

def gradient_color(stops, lum):
    """stops: list of (luminance, rgb) sorted ascending. Piecewise sRGB lerp."""
    if lum <= stops[0][0]:
        return stops[0][1]
    for (l0, c0), (l1, c1) in zip(stops, stops[1:]):
        if lum <= l1:
            t = 0.0 if l1 == l0 else (lum - l0) / (l1 - l0)
            return lerp(c0, c1, t)
    return stops[-1][1]

def main():
    css = open("css/style.css").read()
    root = css.split(":root {")[1].split("}")[0]
    tokens = re.findall(r"(--[\w-]+)\s*:\s*(#[0-9a-fA-F]{6})", root)

    out = []
    out.append("/* Auto-generated by build-themes.py — per-page duo palettes. */")
    out.append("/* Home page carries no data-page attribute and is untouched. */")

    for page, (c1, c2) in DUOS.items():
        rgb1, rgb2 = hex_to_rgb(c1), hex_to_rgb(c2)
        stops = sorted(
            [(0.0, (0, 0, 0)), (rel_lum(rgb1), rgb1),
             (rel_lum(rgb2), rgb2), (1.0, (255, 255, 255))],
            key=lambda s: s[0],
        )
        # Complementary detail spectrum: same method on the hue complements.
        comp1, comp2 = complement(c1), complement(c2)
        crgb1, crgb2 = hex_to_rgb(comp1), hex_to_rgb(comp2)
        detail_stops = sorted(
            [(0.0, (0, 0, 0)), (rel_lum(crgb1), crgb1),
             (rel_lum(crgb2), crgb2), (1.0, (255, 255, 255))],
            key=lambda s: s[0],
        )
        rebound = {}
        for name, val in tokens:
            spec = detail_stops if name in DETAIL_TOKENS else stops
            rebound[name] = rgb_to_hex(gradient_color(spec, rel_lum(hex_to_rgb(val))))
        print(f"{page}: duo {c1}/{c2} detail {comp1}/{comp2}")

        out.append("")
        out.append(f'html[data-page="{page}"] {{')
        for name, _ in tokens:
            out.append(f"  {name}: {rebound[name]};")
        # --overlay follows the original design relationship:
        # night overlay = void at 0.82, day overlay = space-800 at 0.62
        vr, vg, vb = hex_to_rgb(rebound["--void"])
        out.append(f"  --overlay: rgba({vr}, {vg}, {vb}, 0.82);")
        out.append("}")

        sr, sg, sb = hex_to_rgb(rebound["--space-800"])
        out.append(f'html[data-page="{page}"][data-theme="day"] {{')
        out.append(f"  --overlay: rgba({sr}, {sg}, {sb}, 0.62);")
        out.append("}")

    open("css/themes.css", "w").write("\n".join(out) + "\n")
    print("wrote css/themes.css")

if __name__ == "__main__":
    main()
